type Capability = {
  title: string
  blurb: string
  detail: string
  path: string
}

const CAPABILITIES: Capability[] = [
  {
    title: 'Change policy as code',
    blurb: 'Who may approve what, in which environment, in one reviewed file.',
    detail:
      'Halyard evaluates the policy before the deploy starts rather than after somebody complains, so a change that nobody is allowed to approve never reaches the queue in the first place.',
    path: 'M6 5h12v14H6z M9 9h6 M9 12h6 M9 15h4',
  },
  {
    title: 'Approval queue',
    blurb: 'Reviewers see the diff, the blast radius and the last four deploys.',
    detail:
      'An approver gets everything needed to answer in one screen, which is why the median approval at Fernpost Bank closes in thirty-eight seconds instead of waiting for Thursday’s board.',
    path: 'M5 7h14 M5 12h9 M5 17h11 M17.5 16l2 2 3-4',
  },
  {
    title: 'Evidence bundles',
    blurb: 'A signed record of who asked, who approved, what ran and what it touched.',
    detail:
      'Export a quarter as a single PDF, or push it continuously into Vanta, Drata or your own object store. The record is generated by the deploy, not typed up afterwards.',
    path: 'M7 4h7l4 4v12H7z M14 4v4h4 M10 13h5 M10 16h5',
  },
  {
    title: 'Blast-radius preview',
    blurb: 'What this change touches, resolved before it lands.',
    detail:
      'Halyard walks your service graph and your data contracts, then flags every downstream service, queue and dataset in scope — and highlights the ones sitting inside an active freeze.',
    path: 'M12 4v4 M12 16v4 M4 12h4 M16 12h4 M12 9.5a2.5 2.5 0 100 5 2.5 2.5 0 000-5',
  },
  {
    title: 'One-click rollback',
    blurb: 'The previous known-good release stays warm for seventy-two hours.',
    detail:
      'Rolling back is a single approved action rather than an incident-time scramble, and it is evidenced exactly like any other change so the record of the bad hour survives.',
    path: 'M5 9a7 7 0 1 1 0 6 M5 9V4 M5 9h5',
  },
  {
    title: 'Freeze windows',
    blurb: 'Declare a freeze for a service, a region or the whole estate.',
    detail:
      'Emergency changes still get through during a freeze, but they carry a break-glass record naming the person who opened it and the incident that justified it.',
    path: 'M12 3v18 M4.5 7.5l15 9 M19.5 7.5l-15 9',
  },
]

export default function Capabilities() {
  return (
    <section id="capabilities" className="bg-[#F7F5F1] py-24">
      <div className="mx-auto max-w-6xl px-6">
        <div className="max-w-2xl">
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-[#B57A16]">What Halyard does</p>
          <h2 className="mt-4 text-4xl font-bold tracking-tight text-[#0B1524] sm:text-[2.75rem]">
            Six pieces, one control plane
          </h2>
          <p className="mt-5 text-lg leading-relaxed text-slate-600">
            Most teams already have a pipeline they trust. Halyard does not replace it — it wraps the last two minutes
            of it, where the decisions that auditors care about actually happen.
          </p>
        </div>

        <div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {CAPABILITIES.map((capability) => (
            <article
              key={capability.title}
              data-testid="capability-card"
              className="rounded-2xl border border-[#E3DDD2] bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
            >
              <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#0B1524]">
                <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" aria-hidden="true" focusable="false">
                  <path
                    d={capability.path}
                    stroke="#F2A93B"
                    strokeWidth="1.6"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              </span>
              <h3 className="mt-5 text-lg font-semibold tracking-tight text-[#0B1524]">{capability.title}</h3>
              <p className="mt-2 text-sm font-medium text-slate-700">{capability.blurb}</p>
              <p className="mt-3 text-sm leading-relaxed text-slate-500">{capability.detail}</p>
            </article>
          ))}
        </div>
      </div>
    </section>
  )
}
